#!/usr/bin/env python3
"""Tests for extract_mobs.py.

Expected values are hand-derived from the Phoenix server source
(mobutils.cpp @ 0f3f8fc) - each assertion's arithmetic is worked out in
the comment above it, NOT generated by running the extractor.

Run: python3 Whetstone/tools/test_extract_mobs.py
"""

import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import extract_mobs as X  # noqa: E402


class FormulaTests(unittest.TestCase):
    def test_base_to_rank(self):
        # GetBaseToRank, integer division:
        # C(3) @ 20: 4 + (19 * 40) // 100 = 4 + 7
        self.assertEqual(11, X.base_to_rank(3, 20))
        # A(1) @ 75: 5 + (74 * 50) // 100 = 5 + 37
        self.assertEqual(42, X.base_to_rank(1, 75))
        # G(7) @ 75: 2 + (74 * 20) // 100 = 2 + 14
        self.assertEqual(16, X.base_to_rank(7, 75))
        # invalid rank (NON job grade 0)
        self.assertEqual(0, X.base_to_rank(0, 50))

    def test_base_def_eva(self):
        # C @ 20: floor(5 + 19 * 2.8) = floor(58.2)
        self.assertEqual(58, X.base_def_eva(3, 20))
        # A @ 75: floor(153 + 25 * 5.0)
        self.assertEqual(278, X.base_def_eva(1, 75))
        # B @ 75: floor(147 + 25 * 4.9) = floor(269.5)
        self.assertEqual(269, X.base_def_eva(2, 75))
        # E @ 51: floor(126 + 1 * 4.5)
        self.assertEqual(130, X.base_def_eva(5, 51))

    def test_sub_job_stats(self):
        # D @ 30 with stat 13: max(floor(13 / (5.0 - 0.05*9)), 1)
        #   = floor(13 / 4.55) = 2
        self.assertEqual(2, X.sub_job_stats(4, 30, 13))
        # A @ 75 with stat 42: floor(42 / (2.7 - 0.001*30))
        #   = floor(42 / 2.67) = floor(15.73) = 15
        self.assertEqual(15, X.sub_job_stats(1, 75, 42))

    def test_eva_rank_mapping(self):
        # JobSkillRankToBaseEvaRank: best (lowest) rank wins
        self.assertEqual(1, X.eva_rank_from_skill_ranks(1, 5))
        self.assertEqual(3, X.eva_rank_from_skill_ranks(6, 10))
        self.assertEqual(4, X.eva_rank_from_skill_ranks(9, 9))
        self.assertEqual(5, X.eva_rank_from_skill_ranks(10, 11))
        self.assertEqual(3, X.eva_rank_from_skill_ranks(11, 11))  # fallback

    def test_split_values(self):
        values = X.split_values("1,'O''Kane',NULL,0x1F2D,-2,3.5,'a\\'b'")

        self.assertEqual(
            [1, "O'Kane", None, '0x1F2D', -2, 3.5, "a'b"], values)


FIXTURE_ZONE_H = """
enum ZONEID : uint16
{
    ZONE_PHANAUET_CHANNEL = 1,
    ZONE_WEST_RONFAURE    = 100,
};
"""

# 28 columns; 0 (poolid), 1 (name), 3 (speciesid), 5 (mJob), 6 (sJob),
# 7 (cmbSkill), 8 (cmbDelay), 14 (mobType) are read.
POOL_ROW = ("INSERT INTO `mob_pools` VALUES "
            "(%d,'%s','%s',%d,0x01,%d,%d,2,240,100,0,0,0,0,%d,"
            "0,0,0,0,0,0,0,1,0,0,0,4,4);")

# variant with explicit cmbSkill/cmbDelay (h2h fixture)
POOL_ROW_CMB = ("INSERT INTO `mob_pools` VALUES "
                "(%d,'%s','%s',%d,0x01,%d,%d,%d,%d,100,0,0,0,0,%d,"
                "0,0,0,0,0,0,0,1,0,0,0,4,4);")

FIXTURE_SQL = {
    'mob_species_system.sql': [
        # speciesID 10: VIT rank C(3), AGI rank D(4), DEF rank C(3)
        "INSERT INTO `mob_species_system` VALUES "
        "(10,'Snipper',5,'Crab',1,'Aquan',40,100,100,"
        "4,4,3,4,4,4,5,1,3,1,3,0.0,2,0);",
        "INSERT INTO `mob_species_system` VALUES "
        "(11,'Big Jaw',5,'Crab',1,'Aquan',40,100,100,"
        "4,4,3,4,4,4,5,1,3,1,3,0.0,2,0);",
    ],
    'mob_pools.sql': [
        POOL_ROW % (500, 'Snipper', 'Snipper', 10, 1, 0, 0),    # WAR/NON
        POOL_ROW % (501, 'Sub_Crab', 'Sub_Crab', 10, 1, 3, 0),  # WAR/WHM
        POOL_ROW % (502, 'Rock_Crab', 'Rock_Crab', 10, 1, 13, 0),  # WAR/NIN
        POOL_ROW % (503, 'Pool_Crab', 'Pool_Crab', 11, 1, 0, 0),
        POOL_ROW % (504, 'Mod_Crab', 'Mod_Crab', 10, 1, 0, 2),  # NM flag
        # MNK-style puncher: cmbSkill 1 (hand_to_hand), cmbDelay 480
        POOL_ROW_CMB % (505, 'Fist_Crab', 'Fist_Crab', 10, 2, 0, 1, 480, 0),
    ],
    'mob_groups.sql': [
        "INSERT INTO `mob_groups` VALUES (1,500,1,'Snipper',0,128,0,0,0,0,NULL);",
        "INSERT INTO `mob_groups` VALUES (2,502,1,'Rock_Crab',0,128,0,0,0,0,NULL);",
        "INSERT INTO `mob_groups` VALUES (3,503,1,'Pool_Crab',0,128,0,0,0,0,NULL);",
        "INSERT INTO `mob_groups` VALUES (4,504,1,'Mod_Crab',0,128,0,0,0,0,NULL);",
        "INSERT INTO `mob_groups` VALUES (5,501,1,'Sub_Crab',0,128,0,0,0,0,NULL);",
        "INSERT INTO `mob_groups` VALUES (6,505,1,'Fist_Crab',0,128,0,0,0,0,NULL);",
        "INSERT INTO `mob_groups` VALUES (1,501,100,'Sub_Crab',0,128,0,0,0,0,NULL);",
    ],
    'mob_spawn_points.sql': [
        # zone 1 mobids: 0x1000000 | (1 << 12) | n
        "INSERT INTO `mob_spawn_points` VALUES "
        "(16781313,0,'Snipper','Snipper',1,20,25,1.0,1.0,1.0,0);",
        # second spawn point of the same group -> must dedupe
        "INSERT INTO `mob_spawn_points` VALUES "
        "(16781314,0,'Snipper','Snipper',1,20,25,2.0,2.0,2.0,0);",
        "INSERT INTO `mob_spawn_points` VALUES "
        "(16781315,0,'Rock_Crab','Rock Crab',2,30,30,1.0,1.0,1.0,0);",
        "INSERT INTO `mob_spawn_points` VALUES "
        "(16781316,0,'Pool_Crab','Pool Crab',3,20,20,1.0,1.0,1.0,0);",
        "INSERT INTO `mob_spawn_points` VALUES "
        "(16781317,0,'Mod_Crab','Mod Crab',4,20,20,1.0,1.0,1.0,0);",
        "INSERT INTO `mob_spawn_points` VALUES "
        "(16781318,0,'Sub_Crab','Sub Crab',5,30,30,1.0,1.0,1.0,0);",
        "INSERT INTO `mob_spawn_points` VALUES "
        "(16781319,0,'Fist_Crab','Fist Crab',6,20,20,1.0,1.0,1.0,0);",
        # zone 100 mobid: 0x1000000 | (100 << 12) | 1 = 17186817
        "INSERT INTO `mob_spawn_points` VALUES "
        "(17186817,0,'Sub_Crab','Sub Crab',1,30,30,1.0,1.0,1.0,0);",
    ],
    'skill_ranks.sql': [
        # evasion ranks: war=6, whm=10, nin=1, everything else 8
        "INSERT INTO `skill_ranks` VALUES (23,'evasion',"
        "6,2,10,10,8,1,8,8,8,8,8,8,1,8,8,8,8,8,8,8,8,8);",
    ],
    'traits.sql': [
        # NIN Evasion Bonus: rank 1 @5 (+10 EVA), rank 2 @25 (+22 EVA)
        "INSERT INTO `traits` VALUES (19,'evasion_bonus',13,5,1,68,10,NULL,0);",
        "INSERT INTO `traits` VALUES (19,'evasion_bonus',13,25,2,68,22,NULL,0);",
    ],
    'mob_pool_mods.sql': [
        "INSERT INTO `mob_pool_mods` VALUES (504,1,12,0);",   # +12 DEF
        "INSERT INTO `mob_pool_mods` VALUES (504,68,99,1);",  # mobMod: ignore
        # Telegraph TP mods: REGAIN 368 / STORETP 73 on the NM pool
        "INSERT INTO `mob_pool_mods` VALUES (504,368,20,0);",
        "INSERT INTO `mob_pool_mods` VALUES (504,73,10,0);",
        # is_mob_mod = 1 with a TP mod id is a mobMod, NOT a modifier
        "INSERT INTO `mob_pool_mods` VALUES (504,368,99,1);",
    ],
    'mob_species_mods.sql': [
        "INSERT INTO `mob_species_mods` VALUES (11,68,20,0);",  # +20 EVA
        # species-level SUBTLE_BLOW joins pool-level TP mods
        "INSERT INTO `mob_species_mods` VALUES (10,289,5,0);",
    ],
}


def build_fixture(root: Path):
    (root / 'sql').mkdir(parents=True)
    (root / 'src' / 'map').mkdir(parents=True)
    (root / 'src' / 'map' / 'zone.h').write_text(FIXTURE_ZONE_H)

    for name, rows in FIXTURE_SQL.items():
        (root / 'sql' / name).write_text('\n'.join(rows) + '\n')


class ExtractionTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.tmp = tempfile.TemporaryDirectory()
        root = Path(cls.tmp.name)
        build_fixture(root)
        cls.data = X.ServerData(root)
        cls.mobs, cls.accounting = X.extract(cls.data)

    @classmethod
    def tearDownClass(cls):
        cls.tmp.cleanup()

    def entry(self, zone, name):
        entries = self.mobs[zone][name]
        self.assertEqual(1, len(entries))
        return entries[0]

    def test_war_non_baseline(self):
        # Snipper, WAR/NON, species ranks VIT C / AGI D / DEF C, lvl 20-25.
        # Level 20:
        #   fVIT = 4+(19*40)//100 = 11, mVIT(grade 4) = 3+(19*35)//100 = 9,
        #   sub NON = 0 -> VIT 20
        #   fAGI(D) = 9, mAGI(grade 3) = 11 -> AGI 20
        #   DEF = 8 + 20//2 + floor(5 + 19*2.8)=58 -> 76
        #   EVA: WAR evasion rank 6 -> base rank C -> 58 + 20//2 = 68
        # Level 25:
        #   fVIT = 4+(24*40)//100 = 13, mVIT = 3+(24*35)//100 = 11 -> 24
        #   fAGI = 11, mAGI = 13 -> 24
        #   DEF = 8 + 12 + floor(5 + 24*2.8)=72 -> 92
        #   EVA = 72 + 12 = 84
        e = self.entry(1, 'Snipper')

        self.assertEqual((20, 25), (e['min_level'], e['max_level']))
        self.assertEqual({'vit': 20, 'agi': 20, 'def': 76, 'eva': 68},
                         e['levels'][20])
        self.assertEqual({'vit': 24, 'agi': 24, 'def': 92, 'eva': 84},
                         e['levels'][25])
        self.assertEqual('WAR', e['mjob'])
        self.assertFalse(e['nm'])

    def test_per_level_rows_are_exact(self):
        # Level 21 (an INTERIOR level, must be exact, not interpolated):
        #   fVIT = 4+(20*40)//100 = 12, mVIT = 3+(20*35)//100 = 10 -> VIT 22
        #   fAGI = 3+(20*35)//100 = 10, mAGI = 4+(20*40)//100 = 12 -> AGI 22
        #   DEF = 8 + 22//2 + floor(5 + 20*2.8)=61 -> 80
        #   EVA = 61 + 22//2 = 72
        e = self.entry(1, 'Snipper')

        self.assertEqual(6, len(e['levels']))  # 20..25 inclusive
        self.assertEqual({'vit': 22, 'agi': 22, 'def': 80, 'eva': 72},
                         e['levels'][21])

    def test_spawn_points_deduped(self):
        # Two spawn points of the same group -> one entry (asserted in
        # self.entry via len == 1)
        self.entry(1, 'Snipper')

    def test_subjob_halved_outside_original_zones(self):
        # Sub Crab WAR/WHM @30 in zone 1 (not a subjob zone):
        #   fVIT = 4+(29*40)//100 = 15, mVIT = 3+(29*35)//100 = 13,
        #   sVIT = base_to_rank(WHM grade 4, 30)=13 // 2 = 6 -> VIT 34
        #   fAGI(D) = 13, mAGI = 4+(29*40)//100 = 15,
        #   sAGI = base_to_rank(WHM grade 5, 30)=11 // 2 = 5 -> AGI 33
        #   DEF = 8 + 17 + floor(5+29*2.8)=86 -> 111
        #   EVA: min(WAR 6, WHM 10) -> rank C -> 86 + 16 = 102
        e = self.entry(1, 'Sub Crab')

        self.assertEqual({'vit': 34, 'agi': 33, 'def': 111, 'eva': 102},
                         e['levels'][30])

    def test_subjob_formula_inside_original_zones(self):
        # Same pool in zone 100 (West Ronfaure, subjob zone, sLvl < 50):
        #   sVIT = GetSubJobStats(D, 30, 13) = floor(13/4.55) = 2 -> VIT 30
        #   sAGI = GetSubJobStats(E, 30, 11) = floor(11/(3.8+0.2)) = 2 -> AGI 30
        #   DEF = 8 + 15 + 86 = 109; EVA = 86 + 15 = 101
        e = self.entry(100, 'Sub Crab')

        self.assertEqual({'vit': 30, 'agi': 30, 'def': 109, 'eva': 101},
                         e['levels'][30])

    def test_traits_apply_highest_rank(self):
        # Rock Crab WAR/NIN @30: NIN Evasion Bonus rank 2 (+22) applies.
        #   VIT: 15 + 13 + base_to_rank(NIN grade 3, 30)=15 // 2 = 7 -> 35
        #   AGI: 13 + 15 + base_to_rank(NIN grade 2, 30)=17 // 2 = 8 -> 36
        #   DEF = 8 + 17 + 86 = 111
        #   EVA: min(WAR 6, NIN 1) -> rank A -> floor(6+29*3.0)=93
        #        93 + 36//2 + 22 = 133
        e = self.entry(1, 'Rock Crab')

        self.assertEqual({'vit': 35, 'agi': 36, 'def': 111, 'eva': 133},
                         e['levels'][30])

    def test_species_mods(self):
        # Pool Crab (species 11, +20 EVA species mod) @20: EVA 68 + 20
        e = self.entry(1, 'Pool Crab')

        self.assertEqual(88, e['levels'][20]['eva'])
        self.assertEqual(76, e['levels'][20]['def'])

    def test_pool_mods_and_nm_flag(self):
        # Mod Crab @20: +12 DEF pool mod -> 88; the is_mob_mod=1 row
        # (+99 EVA) must be ignored -> EVA stays 68. mobType bit 2 -> NM.
        e = self.entry(1, 'Mod Crab')

        self.assertEqual(88, e['levels'][20]['def'])
        self.assertEqual(68, e['levels'][20]['eva'])
        self.assertTrue(e['nm'])

    def test_combat_delay_and_h2h(self):
        # mob_pools cmbDelay/cmbSkill feed Telegraph's TP ledger:
        # the fixture POOL_ROW carries cmbSkill 2 / cmbDelay 240
        e = self.entry(1, 'Snipper')

        self.assertEqual(240, e['cmb_delay'])
        self.assertFalse(e['h2h'])

        # cmbSkill 1 = SKILL_HAND_TO_HAND
        fist = self.entry(1, 'Fist Crab')

        self.assertEqual(480, fist['cmb_delay'])
        self.assertTrue(fist['h2h'])

    def test_tp_mods_aggregate_pool_and_species(self):
        # Mod Crab: pool 504 REGAIN 20 + STORETP 10 (is_mob_mod=0),
        # species 10 SUBTLE_BLOW 5; the is_mob_mod=1 REGAIN row is a
        # mobMod and must be ignored
        e = self.entry(1, 'Mod Crab')

        self.assertEqual(
            {'regain': 20, 'store_tp': 10, 'subtle_blow': 5},
            e['tp_mods'])

        # Pool Crab (species 11) has no TP mods at all
        self.assertEqual({}, self.entry(1, 'Pool Crab')['tp_mods'])

    def test_tp_fields_reach_the_lua(self):
        text = X.emit_lua(self.mobs, 'fixture')

        self.assertIn('cmb_delay = 240, h2h = false', text)
        self.assertIn('cmb_delay = 480, h2h = true', text)
        self.assertIn(
            'tp_mods = { regain = 20, store_tp = 10, subtle_blow = 5 }',
            text)
        # entries without TP mods stay lean
        self.assertNotIn('tp_mods = {  }', text)
        self.assertNotIn('tp_mods = { }', text)

    def test_split_emission_balances_across_zones(self):
        with tempfile.TemporaryDirectory() as out:
            out_dir = Path(out) / 'mobs'
            counts = X.emit_split(self.mobs, self.accounting, out_dir,
                                  'fixture')

            # one file per zone + the index
            self.assertEqual({1, 100}, set(counts))
            self.assertTrue((out_dir / 'index.lua').exists())
            self.assertTrue((out_dir / 'zone_1.lua').exists())
            self.assertTrue((out_dir / 'zone_100.lua').exists())

            # index totals must equal extraction accounting
            index_text = (out_dir / 'index.lua').read_text()
            self.assertIn('total_entries = %d'
                          % self.accounting['emitted'], index_text)
            self.assertEqual(self.accounting['emitted'],
                             sum(counts.values()))

            # zone file carries the same exact rows as monolithic mode
            zone1 = (out_dir / 'zone_1.lua').read_text()
            self.assertIn(
                '[21] = { vit = 22, agi = 22, def = 80, eva = 72 }',
                zone1)

    def test_split_raises_on_row_loss(self):
        # Simulate a future bug that drops a zone between extraction
        # and emission: the cross-split conservation check must fire.
        crippled = dict(self.mobs)
        del crippled[100]

        with tempfile.TemporaryDirectory() as out:
            with self.assertRaises(X.ConservationError):
                X.emit_split(crippled, self.accounting,
                             Path(out) / 'mobs', 'fixture')

    def test_singleton_validation_targets(self):
        # Sub Crab in West Ronfaure (zone 100) spawns at exactly 30/30
        zone_names = {'WEST_RONFAURE': 100}
        lines = X.emit_singletons(self.mobs, zone_names)

        self.assertEqual(1, len(lines))
        self.assertIn('Sub Crab', lines[0])
        self.assertIn('Lv.30', lines[0])
        self.assertIn('def=109', lines[0])

    def test_lua_emission_is_loadable_shape(self):
        text = X.emit_lua(self.mobs, 'fixture')

        self.assertIn("['Snipper']", text)
        self.assertIn('[20] = { vit = 20, agi = 20, def = 76, eva = 68 }',
                      text)
        self.assertTrue(text.startswith('-- Generated'))
        self.assertTrue(text.rstrip().endswith('}'))


if __name__ == '__main__':
    unittest.main(verbosity=2)
