--[[
    Whetstone formulas test suite.

    Runs under busted (`busted Whetstone/tests/test_formulas.lua`) or
    plain Lua 5.1+ (`lua5.1 Whetstone/tests/test_formulas.lua`) via the
    inline shim below.

    Expected values are hand-derived from the LandSandBoat source
    (commit fdc24716f825de6b96a3c4c9896cd1c7295c494f), NOT generated by
    running formulas.lua - each `near` constant is worked out in the
    comment above it.
]]

-- ---------------------------------------------------------------------
-- Minimal busted shim for plain-Lua runs
-- ---------------------------------------------------------------------
if type(describe) ~= 'function' then
    local stack  = {}
    local tests  = 0
    local failed = 0

    function describe(name, fn)
        table.insert(stack, name)
        fn()
        table.remove(stack)
    end

    function it(name, fn)
        tests = tests + 1

        local ok, err = pcall(fn)

        if ok then
            print('ok   ' .. table.concat(stack, ' > ') .. ' > ' .. name)
        else
            failed = failed + 1
            print('FAIL ' .. table.concat(stack, ' > ') .. ' > ' .. name)
            print('     ' .. tostring(err))
        end
    end

    local original_assert = assert

    assert = setmetatable(
    {
        are =
        {
            equal = function(expected, actual, msg)
                if expected ~= actual then
                    error((msg or 'assert.are.equal') ..
                        ': expected ' .. tostring(expected) ..
                        ', got ' .. tostring(actual), 2)
                end
            end,
        },

        is_true = function(value, msg)
            if value ~= true then
                error((msg or 'assert.is_true') .. ': got ' .. tostring(value), 2)
            end
        end,

        is_false = function(value, msg)
            if value ~= false then
                error((msg or 'assert.is_false') .. ': got ' .. tostring(value), 2)
            end
        end,

        is_nil = function(value, msg)
            if value ~= nil then
                error((msg or 'assert.is_nil') .. ': got ' .. tostring(value), 2)
            end
        end,

        near = function(expected, actual, tolerance, msg)
            if type(actual) ~= 'number' or math.abs(expected - actual) > tolerance then
                error((msg or 'assert.near') ..
                    ': expected ' .. tostring(expected) ..
                    ' +/- ' .. tostring(tolerance) ..
                    ', got ' .. tostring(actual), 2)
            end
        end,
    },
    {
        __call = function(_, ...)
            return original_assert(...)
        end,
    })

    WHETSTONE_TEST_SUMMARY = function()
        print(string.format('%d tests, %d failures', tests, failed))

        if failed > 0 then
            os.exit(1)
        end
    end
end

-- ---------------------------------------------------------------------
-- Locate formulas.lua relative to this file
-- ---------------------------------------------------------------------
local here = (arg and arg[0] and arg[0]:match('(.*[/\\])')) or ''
package.path = table.concat(
{
    here .. '../?.lua',
    'Whetstone/?.lua',
    '?.lua',
    package.path,
}, ';')

local F = require('formulas')

-- =====================================================================
describe('weapon rank', function()
    it('is floor(dmg / 9)', function()
        -- battleentity.cpp GetMainWeaponRank
        assert.are.equal(5, F.weapon_rank(49))  -- e.g. Juggernaut era axes
        assert.are.equal(0, F.weapon_rank(8))
        assert.are.equal(9, F.weapon_rank(81))
        assert.are.equal(8, F.weapon_rank(80))
    end)

    it('adds +3 to H2H damage before ranking', function()
        assert.are.equal(4, F.weapon_rank(33, true)) -- (33 + 3) / 9
        assert.are.equal(3, F.weapon_rank(32, true)) -- (32 + 3) / 9 = 3.88
    end)
end)

-- =====================================================================
describe('fSTR (player melee)', function()
    -- Tiers: dSTR >= 12 -> +4 | >= 6 -> +6 | >= 1 -> +7 | >= -2 -> +8
    --        >= -7 -> +9 | >= -15 -> +10 | >= -21 -> +12 | else +13
    -- then /4, clamped to [-rank (or -1 at rank 0), rank + 8]

    it('computes interior tiers', function()
        assert.are.equal(6, F.fstr(80, 60, 5))   -- dSTR 20: (20+4)/4
        assert.are.equal(2, F.fstr(60, 60, 5))   -- dSTR 0: (0+8)/4
        assert.are.equal(3, F.fstr(66, 60, 5))   -- dSTR 6: (6+6)/4
    end)

    it('keeps LSB quarter-point fractions (no floor for players)', function()
        assert.are.equal(2.75, F.fstr(64, 60, 5)) -- dSTR 4 -> 11/4
        assert.are.equal(4.25, F.fstr(73, 60, 5)) -- dSTR 13 -> 17/4
    end)

    it('clamps the stat diff window by weapon rank', function()
        -- rank 0: window [-14, 28]. dSTR -30 clamps to -14 -> (-14+10)/4 = -1
        -- which also equals the rank-0 floor of -1
        assert.are.equal(-1, F.fstr(30, 60, 0))
    end)

    it('caps fSTR at rank + 8', function()
        -- rank 10: window [-54, 68]; dSTR 140 clamps to 68 -> 72/4 = 18 = cap
        assert.are.equal(18, F.fstr(200, 60, 10))
    end)

    it('caps fSTR at -rank on the low side', function()
        -- rank 5: dSTR -34 (window edge) -> (-34+13)/4 = -5.25 -> clamp -5
        assert.are.equal(-5, F.fstr(26, 60, 5))
    end)

    it('truncates toward zero with the strict-era integer knob', function()
        -- Matches AirSkyBoat's C++ integer division: dSTR -11 ->
        -- (-11+10)/4 = -0.25 -> 0 (toward zero, NOT floor -1)
        local era = { fstr_integer = true }

        assert.are.equal(0, F.fstr(49, 60, 5, era))
        assert.are.equal(-0.25, F.fstr(49, 60, 5)) -- default keeps fractions
        assert.are.equal(4, F.fstr(73, 60, 5, era)) -- 4.25 -> 4
    end)
end)

describe('fSTR (player ranged, fSTR2)', function()
    it('divides by 2 instead of 4', function()
        -- dSTR 20 -> (20+4)/2 = 12, caps rank 5: [-10, 26]
        assert.are.equal(12, F.fstr_ranged(80, 60, 5))
    end)

    it('uses the special low caps for ranks 0 and 1', function()
        -- rank 0: dSTR -40 clamps to window -14 -> (-14+10)/2 = -2 = floor cap -2
        assert.are.equal(-2, F.fstr_ranged(20, 60, 0))
    end)
end)

describe('fSTR (mob)', function()
    it('returns 1 at level 1 or below', function()
        assert.are.equal(1, F.fstr_mob(50, 50, 1))
    end)

    it('floors and clamps to [lvl/5 - 1, lvl/5 + 5]', function()
        -- lvl 75 window: [14, 20]
        -- dSTR 10 -> (10-1)/4 = 2.25 -> floor 2 -> clamped up to 14
        assert.are.equal(14, F.fstr_mob(70, 60, 75))
        -- dSTR 70 -> (70-4)/4 = 16.5 -> floor 16, inside window
        assert.are.equal(16, F.fstr_mob(130, 60, 75))
        -- dSTR 200 -> 49 -> clamped down to 20
        assert.are.equal(20, F.fstr_mob(260, 60, 75))
    end)
end)

describe('fSTR tier info', function()
    it('reports STR distance to the next tier', function()
        -- dSTR 20 -> 6.0; dSTR 21 -> (21+4)/4 = 6.25
        local info = F.fstr_info(80, 60, 5)

        assert.are.equal(6, info.fstr)
        assert.is_false(info.at_cap)
        assert.are.equal(1, info.str_to_next)
        assert.are.equal(6.25, info.next_fstr)
    end)

    it('skips dead zones created by the value clamp', function()
        -- rank 5, dSTR -40: clamped to window -34 -> value clamp -5.
        -- fSTR stays -5 until dSTR -32 -> (-32+13)/4 = -4.75: 8 STR away.
        local info = F.fstr_info(20, 60, 5)

        assert.are.equal(-5, info.fstr)
        assert.are.equal(8, info.str_to_next)
        assert.are.equal(-4.75, info.next_fstr)
    end)

    it('detects the hard cap', function()
        local info = F.fstr_info(200, 60, 10)

        assert.are.equal(18, info.fstr)
        assert.is_true(info.at_cap)
        assert.is_nil(info.str_to_next)
    end)
end)

-- =====================================================================
describe('hit rate', function()
    it('is 75% at equal acc/eva', function()
        assert.are.equal(0.75, F.hit_rate({ acc = 300, eva = 300 }))
    end)

    it('moves 0.5% per accuracy point', function()
        assert.are.equal(0.80, F.hit_rate({ acc = 310, eva = 300 }))
        assert.are.equal(0.70, F.hit_rate({ acc = 290, eva = 300 }))
    end)

    it('caps at 99% for 1H mainhand and H2H, 95% for 2H/offhand (lsb)', function()
        local p = { acc = 360, eva = 300, profile = 'lsb' } -- raw 1.05

        assert.are.equal(0.99, F.hit_rate(p))

        p.two_handed = true
        assert.are.equal(0.95, F.hit_rate(p))

        p.two_handed = false
        p.offhand = true
        assert.are.equal(0.95, F.hit_rate(p))

        p.offhand = false
        p.h2h = true
        assert.are.equal(0.99, F.hit_rate(p))
    end)

    it('caps at a flat 95% on Phoenix (default profile)', function()
        -- modules/soa/lua/physical_hit_cap.lua override
        local p = { acc = 360, eva = 300 } -- raw 1.05

        assert.are.equal(0.95, F.hit_rate(p)) -- 1H mainhand

        p.h2h = true
        assert.are.equal(0.95, F.hit_rate(p))

        p.h2h = false
        p.two_handed = true
        assert.are.equal(0.95, F.hit_rate(p))
    end)

    it('floors at 20%', function()
        local rate, capped, floored = F.hit_rate({ acc = 100, eva = 300 })

        assert.are.equal(0.20, rate)
        assert.is_false(capped)
        assert.is_true(floored)
    end)

    it('reports when the ceiling is reached', function()
        local _, capped = F.hit_rate({ acc = 348, eva = 300 }) -- raw exactly 0.99

        assert.is_true(capped)
    end)

    it('applies -4 acc per level below the target in corrected zones', function()
        -- 70 vs 75: acc 300 -> 280 -> (75 - 10)% = 65%
        local rate = F.hit_rate(
        {
            acc              = 300,
            eva              = 300,
            attacker_level   = 70,
            target_level     = 75,
            level_correction = true,
        })

        assert.are.equal(0.65, rate)
    end)

    it('gives players no bonus when higher level', function()
        local rate = F.hit_rate(
        {
            acc              = 300,
            eva              = 300,
            attacker_level   = 75,
            target_level     = 70,
            level_correction = true,
        })

        assert.are.equal(0.75, rate)
    end)

    it('ignores level correction outside corrected zones', function()
        local rate = F.hit_rate(
        {
            acc            = 300,
            eva            = 300,
            attacker_level = 70,
            target_level   = 75,
        })

        assert.are.equal(0.75, rate)
    end)

    it('truncates to whole percent for melee rounds when asked', function()
        -- acc - eva = 33 -> 91.5% -> C++ uint8 path -> 91%
        local rate = F.hit_rate({ acc = 333, eva = 300, floor_percent = true })

        assert.near(0.91, rate, 1e-12)
    end)

    it('computes accuracy needed for the cap', function()
        -- lsb 1H: eva + (99 - 75) * 2 = eva + 48
        assert.are.equal(348, F.acc_for_cap({ eva = 300, profile = 'lsb' }))
        -- lsb 2H: eva + 40
        assert.are.equal(340, F.acc_for_cap({ eva = 300, two_handed = true, profile = 'lsb' }))
        -- Phoenix: flat 95% cap -> eva + 40 regardless of weapon class
        assert.are.equal(340, F.acc_for_cap({ eva = 300 }))
        assert.are.equal(340, F.acc_for_cap({ eva = 300, two_handed = true }))
        -- 2H, 5 levels down in a corrected zone: +20 more
        assert.are.equal(360, F.acc_for_cap(
        {
            eva              = 300,
            two_handed       = true,
            attacker_level   = 70,
            target_level     = 75,
            level_correction = true,
        }))
    end)
end)

-- =====================================================================
describe('haste stacking', function()
    it('caps gear haste at 25%', function()
        local h = F.haste({ gear = 0.30 })

        assert.are.equal(0.25, h.gear)
        assert.near(0.05, h.gear_overcap, 1e-12)
        assert.near(0.75, h.multiplier, 1e-12)
    end)

    it('caps magic haste at 43.75%', function()
        local h = F.haste({ magic = 0.50 })

        assert.are.equal(0.4375, h.magic)
        assert.near(0.0625, h.magic_overcap, 1e-12)
    end)

    it('caps ability haste at 25%', function()
        local h = F.haste({ ability = 0.30 })

        assert.are.equal(0.25, h.ability)
        assert.near(0.05, h.ability_overcap, 1e-12)
    end)

    it('adds 2H ability haste only for 2H weapons', function()
        local one_hand = F.haste({ ability = 0.10, two_hand_ability = 0.10 })
        local two_hand = F.haste({ ability = 0.10, two_hand_ability = 0.10, two_handed = true })

        assert.near(0.10, one_hand.ability, 1e-12)
        assert.near(0.20, two_hand.ability, 1e-12)
    end)

    it('clamps the total at the server delay reduction cap (80%)', function()
        local h = F.haste({ magic = 0.4375, ability = 0.25, gear = 0.25 })

        assert.near(0.20, h.multiplier, 1e-12)
        assert.near(0.80, h.total, 1e-12)
        assert.near(0.1375, h.total_overcap, 1e-12)
    end)

    it('stacks a typical era setup without clamping', function()
        -- Haste spell 15% + 10% gear = 25% -> 0.75x delay
        local h = F.haste({ magic = 0.15, gear = 0.10 })

        assert.near(0.75, h.multiplier, 1e-12)
        assert.near(0, h.total_overcap, 1e-12)
    end)

    it('honors a profile delay reduction cap (93% ToAU option)', function()
        local h = F.haste(
        {
            magic   = 0.4375,
            ability = 0.25,
            gear    = 0.25,
            profile = { delay_reduction_cap = 0.93 },
        })

        assert.near(0.07, h.multiplier, 1e-12)
        assert.near(0.93, h.total, 1e-12)
        assert.near(0.0075, h.total_overcap, 1e-12)
    end)
end)

describe('weapon delay', function()
    it('converts delay units to milliseconds', function()
        assert.near(8000, F.weapon_delay_ms({ delay = 480 }), 1e-9)
    end)

    it('applies the haste multiplier', function()
        assert.near(5625, F.weapon_delay_ms({ delay = 450, haste_multiplier = 0.75 }), 1e-9)
    end)

    it('sums both weapons and applies dual wield', function()
        -- (200 + 200) * 1000/60 * (1 - 0.25) = 5000
        local ms = F.weapon_delay_ms({ delay = 200, sub_delay = 200, dual_wield = 0.25 })

        assert.near(5000, ms, 1e-6)
    end)

    it('clamps at 20% of base delay', function()
        local ms = F.weapon_delay_ms({ delay = 480, haste_multiplier = 0.1 })

        assert.near(1600, ms, 1e-9) -- 8000 * 0.2
    end)
end)

-- =====================================================================
describe('pDIF', function()
    -- All expectations below are hand-derived from calculateMeleePDIF:
    --   E = spike * 1.0 + (1 - spike) * mean(lower, upper) * 1.025

    it('wRatio 1.0 (attack == defense, sword)', function()
        -- upper = 1 + 0.3 = 1.3
        -- lower = 1176/1024 - 448/1024 = 728/1024 = 0.7109375
        -- spike = clamp(0.5 * 1.2, 0, 1/3) = 1/3
        -- E_roll = (0.7109375 + 1.3)/2 * 1.025 = 1.03060546875
        -- E = (1 + 2 * 1.03060546875) / 3
        local r = F.melee_pdif({ attack = 500, defense = 500, weapon = 'sword', profile = 'lsb' })

        assert.near(0.7109375, r.lower, 1e-12)
        assert.near(1.3, r.upper, 1e-12)
        assert.near(1 / 3, r.spike_chance, 1e-12)
        assert.near(3.0612109375 / 3, r.expected, 1e-12)
        assert.is_false(r.at_cap)
    end)

    it('wRatio 2.0 (great axe)', function()
        -- upper = min(2.375, 3.75) = 2.375
        -- lower = (2 * 1176 - 775)/1024 = 1577/1024 = 1.5400390625
        -- spike = 0
        -- E = (1.5400390625 + 2.375)/2 * 1.025 = 2.00645751953125
        local r = F.melee_pdif({ attack = 1000, defense = 500, weapon = 'great_axe', profile = 'lsb' })

        assert.near(1.5400390625, r.lower, 1e-12)
        assert.near(2.375, r.upper, 1e-12)
        assert.near(0, r.spike_chance, 1e-12)
        assert.near(2.00645751953125, r.expected, 1e-12)
    end)

    it('wRatio 0.2 (very low attack)', function()
        -- upper = 0.2 + 0.5 = 0.7, lower = 0 (wRatio < 0.38), spike = 0
        -- E = 0.35 * 1.025 = 0.35875
        local r = F.melee_pdif({ attack = 100, defense = 500, weapon = 'sword', profile = 'lsb' })

        assert.near(0.35875, r.expected, 1e-12)
    end)

    it('wRatio 0.6 (flat-1.0 upper band plus spike)', function()
        -- upper = 1 (0.5 <= w < 0.7)
        -- lower = (0.6 * 1176 - 448)/1024 = 257.6/1024 = 0.2515625
        -- spike = (0.5 - 0.4) * 1.2 = 0.12
        -- E = 0.12 + 0.88 * (0.2515625 + 1)/2 * 1.025 = 0.6844546875
        local r = F.melee_pdif({ attack = 300, defense = 500, weapon = 'sword', profile = 'lsb' })

        assert.near(0.12, r.spike_chance, 1e-12)
        assert.near(0.6844546875, r.expected, 1e-12)
    end)

    it('pins at the per-weapon final cap', function()
        -- ratio 5, dagger cap 3.25: lower = min(4.625, 3.25), upper = min(5.375, 3.25)
        -- E = 3.25 * 1.025 = 3.33125
        local r = F.melee_pdif({ attack = 2500, defense = 500, weapon = 'dagger', profile = 'lsb' })

        assert.near(3.25, r.lower, 1e-12)
        assert.near(3.25, r.upper, 1e-12)
        assert.near(3.33125, r.expected, 1e-12)
        assert.near(3.25 * 1.05, r.roll_max, 1e-12)
        assert.is_true(r.at_cap)
    end)

    it('adds +1 wRatio and +1 cap on crits', function()
        -- attack 1000 def 500 crit, scythe: wRatio 3, cap 4 + 1 = 5
        -- upper = min(3.375, 5), lower = min(3 - 0.375, 5) = 2.625
        -- E = 3.0 * 1.025 = 3.075
        local r = F.melee_pdif({ attack = 1000, defense = 500, weapon = 'scythe', crit = true, profile = 'lsb' })

        assert.are.equal(3, r.wratio)
        assert.are.equal(5, r.final_cap)
        assert.near(3.075, r.expected, 1e-12)
    end)

    it('applies crit damage bonus to rolls but not the spike', function()
        -- same as above with +10% crit damage: E = 3.075 * 1.1
        local r = F.melee_pdif(
        {
            attack         = 1000,
            defense        = 500,
            weapon         = 'scythe',
            crit           = true,
            crit_dmg_bonus = 0.10,
            profile        = 'lsb',
        })

        assert.near(3.075 * 1.1, r.expected, 1e-12)
    end)

    it('shifts both bounds down by 3/64 per level in corrected zones', function()
        -- 70 vs 75, attack = defense, sword: factor = -5 * 3/64 = -0.234375
        -- upper 1.3 -> 1.065625, lower 0.7109375 -> 0.4765625
        -- E_roll = (0.4765625 + 1.065625)/2 * 1.025 = 0.79037109375
        -- E = (1 + 2 * 0.79037109375)/3
        local r = F.melee_pdif(
        {
            attack           = 500,
            defense          = 500,
            weapon           = 'sword',
            attacker_level   = 70,
            target_level     = 75,
            level_correction = true,
        })

        assert.near(-0.234375, r.level_factor, 1e-12)
        assert.near(2.5807421875 / 3, r.expected, 1e-12)
    end)

    it('never gives players positive level correction', function()
        local r = F.melee_pdif(
        {
            attack           = 500,
            defense          = 500,
            weapon           = 'sword',
            attacker_level   = 75,
            target_level     = 70,
            level_correction = true,
        })

        assert.near(0, r.level_factor, 1e-12)
    end)

    it('applies the WS attack multiplier before the ratio', function()
        local r = F.melee_pdif(
        {
            attack        = 300,
            defense       = 300,
            weapon        = 'sword',
            ws_attack_mod = 2.0,
        })

        assert.near(2.0, r.wratio, 1e-12)
    end)

    it('applies ignored defense before the ratio', function()
        -- floor(300 * (1 - 0.5)) = 150 -> ratio 2
        local r = F.melee_pdif(
        {
            attack             = 300,
            defense            = 300,
            weapon             = 'sword',
            ignored_def_factor = 0.5,
        })

        assert.near(2.0, r.wratio, 1e-12)
    end)

    it('computes attack needed for the pDIF cap', function()
        -- lsb sword vs 300 def: ceil((3.25 - 0.375) * 300) = 863
        assert.are.equal(863, F.attack_for_pdif_cap({ defense = 300, weapon = 'sword', profile = 'lsb' }))
        -- lsb great axe: ceil(3.375 * 300) = 1013
        assert.are.equal(1013, F.attack_for_pdif_cap({ defense = 300, weapon = 'great_axe', profile = 'lsb' }))
        -- Phoenix (2.0 cap, any melee weapon): ceil(1.625 * 300) = 488
        assert.are.equal(488, F.attack_for_pdif_cap({ defense = 300, weapon = 'sword' }))
        assert.are.equal(488, F.attack_for_pdif_cap({ defense = 300, weapon = 'great_axe' }))
    end)
end)

-- =====================================================================
describe('pDIF (Phoenix era caps)', function()
    it('pins every melee weapon at 2.0', function()
        -- wRatio 2, sword: upper = min(2.375, 2.0) = 2.0
        -- lower (1.51 <= w < 2.44 branch, NOT min'd with the cap):
        --   (2 * 1176 - 775)/1024 = 1577/1024 = 1.5400390625
        -- E = (1.5400390625 + 2.0)/2 * 1.025 = 1.81427001953125
        local r = F.melee_pdif({ attack = 1000, defense = 500, weapon = 'sword' })

        assert.are.equal(2, r.final_cap)
        assert.near(2.0, r.upper, 1e-12)
        assert.near(1.5400390625, r.lower, 1e-12)
        assert.near(1.81427001953125, r.expected, 1e-12)
        assert.is_true(r.at_cap)
    end)

    it('caps crits at 3.0 (2.0 + 1)', function()
        -- wRatio 3: upper = min(3.375, 3) = 3
        -- lower (>= 2.44 branch) = min(3 - 0.375, 3) = 2.625
        -- E = (2.625 + 3)/2 * 1.025 = 2.8828125
        local r = F.melee_pdif({ attack = 1000, defense = 500, weapon = 'sword', crit = true })

        assert.are.equal(3, r.final_cap)
        assert.near(2.8828125, r.expected, 1e-12)
    end)

    it('keeps 3.0 caps for ranged skills', function()
        -- modules/wotg/lua/pdif_caps_revert.lua: archery/marks/throwing = 3
        assert.are.equal(3.0, F.PROFILES.phoenix.pdif_caps.archery)
        assert.are.equal(3.0, F.PROFILES.phoenix.pdif_caps.marksmanship)
        assert.are.equal(3.0, F.PROFILES.phoenix.pdif_caps.throwing)
    end)

    it('leaves sub-cap curves identical to upstream', function()
        -- wRatio 1.0 never touches the cap, so Phoenix == lsb here
        local phoenix = F.melee_pdif({ attack = 500, defense = 500, weapon = 'sword' })
        local lsb     = F.melee_pdif({ attack = 500, defense = 500, weapon = 'sword', profile = 'lsb' })

        assert.near(lsb.expected, phoenix.expected, 1e-12)
    end)
end)

-- =====================================================================
describe('alpha', function()
    it('matches the legacy table', function()
        assert.near(1.00, F.alpha(5), 1e-12)
        assert.near(0.99, F.alpha(6), 1e-12)
        assert.near(0.91, F.alpha(59), 1e-12)
        assert.near(0.90, F.alpha(60), 1e-12)
        assert.near(0.90, F.alpha(61), 1e-12)
        assert.near(0.89, F.alpha(62), 1e-12)
        assert.near(0.83, F.alpha(75), 1e-12)
        assert.near(0.85, F.alpha(99), 1e-12)
    end)
end)

describe('fTP', function()
    local table_15 = { 1.0, 1.5, 2.0 }

    it('returns 1 with no table or below 1000 TP', function()
        assert.are.equal(1, F.ftp(1500, nil))
        assert.are.equal(1, F.ftp(999, table_15))
    end)

    it('interpolates linearly between anchors', function()
        assert.near(1.0, F.ftp(1000, table_15), 1e-12)
        assert.near(1.25, F.ftp(1500, table_15), 1e-12)
        assert.near(1.5, F.ftp(2000, table_15), 1e-12)
        assert.near(1.75, F.ftp(2500, table_15), 1e-12)
        assert.near(2.0, F.ftp(3000, table_15), 1e-12)
    end)
end)

describe('TP factor', function()
    it('returns 0 with no table, table[1] below 1000 TP', function()
        assert.are.equal(0, F.tp_factor(1500, nil))
        assert.near(0.1, F.tp_factor(500, { 0.1, 0.25, 0.5 }), 1e-12)
    end)

    it('interpolates like fTP otherwise', function()
        assert.near(0.25, F.tp_factor(2000, { 0.1, 0.25, 0.5 }), 1e-12)
        assert.near(0.375, F.tp_factor(2500, { 0.1, 0.25, 0.5 }), 1e-12)
    end)
end)

describe('WSC', function()
    it('floors each stat contribution separately', function()
        -- floor(77 * 0.3) + floor(64 * 0.5) = 23 + 32
        local wsc = F.wsc({ str = 77, mnd = 64 }, { str = 0.3, mnd = 0.5 })

        assert.are.equal(55, wsc)
    end)

    it('ignores missing mods', function()
        assert.are.equal(0, F.wsc({ str = 100 }, {}))
    end)
end)

describe('crit rate', function()
    it('matches the dDEX bonus table', function()
        assert.are.equal(0, F.crit_rate_from_dex(66, 60))     -- diff 6
        assert.are.equal(0.01, F.crit_rate_from_dex(67, 60))  -- diff 7
        assert.are.equal(0.02, F.crit_rate_from_dex(74, 60))  -- diff 14
        assert.are.equal(0.03, F.crit_rate_from_dex(80, 60))  -- diff 20
        assert.are.equal(0.04, F.crit_rate_from_dex(90, 60))  -- diff 30
        assert.near(0.05, F.crit_rate_from_dex(100, 60), 1e-12) -- diff 40 -> (40-35)/100
        assert.near(0.15, F.crit_rate_from_dex(110, 60), 1e-12) -- diff 50
        assert.are.equal(0.15, F.crit_rate_from_dex(150, 60)) -- diff > 50
    end)

    it('starts at 5% and never drops below it', function()
        assert.near(0.08, F.crit_rate({ dex = 80, target_agi = 60 }), 1e-12)
        assert.near(0.05, F.crit_rate({ dex = 10, target_agi = 100, bonus = -0.5 }), 1e-12)
    end)

    it('adds the crit-varies TP factor', function()
        local rate = F.crit_rate(
        {
            dex         = 80,
            target_agi  = 60,
            tp          = 2000,
            crit_varies = { 0.1, 0.25, 0.5 },
        })

        assert.near(0.05 + 0.03 + 0.25, rate, 1e-12)
    end)
end)

-- =====================================================================
describe('weapon skill damage', function()
    -- Shared scenario:
    --   D 50, fSTR 6, STR 100 with 50% mod -> WSC 50, alpha 0.83
    --   mainBase = floor(50 + 6 + 50 * 0.83) = floor(97.5) = 97
    --   attack 600 vs defense 300 -> wRatio 2 -> E[pDIF] = 2.00645751953125
    --   (great axe and axe both leave the 2.375 upper bound uncapped)
    --   acc = eva -> base 75%; first hit +100 acc -> capped
    local EPDIF = 2.00645751953125

    local function scenario(overrides)
        local p =
        {
            weapon_dmg     = 50,
            fstr           = 6,
            stats          = { str = 100 },
            ws             = { ftp = { 1.0, 1.5, 2.0 }, num_hits = 2, mods = { str = 0.5 } },
            tp             = 1000,
            attack         = 600,
            defense        = 300,
            acc            = 300,
            eva            = 300,
            attacker_level = 75,
            target_level   = 75,
            alpha          = 0.83,
            weapon         = 'great_axe',
            profile        = 'lsb', -- keep modern caps so EPDIF stays uncapped
        }

        for key, value in pairs(overrides or {}) do
            p[key] = value
        end

        return p
    end

    it('builds mainBase = floor(D + fSTR + WSC * alpha)', function()
        local r = F.ws_damage(scenario())

        assert.are.equal(50, r.wsc)
        assert.are.equal(97, r.main_base)
    end)

    it('gives the first hit +100 accuracy and caps by weapon class', function()
        local r = F.ws_damage(scenario())

        -- 2H: raw (75 + 50)% caps at 95%; extra hits stay at 75%
        assert.are.equal(0.95, r.first_hit_rate)
        assert.are.equal(0.75, r.extra_hit_rate)
    end)

    it('computes a two-hit 2H weapon skill', function()
        -- E = 97 * 1.0 * EPDIF * 0.95  (first)
        --   + 97 * 1.0 * EPDIF * 0.75  (second, fTP reset to 1)
        local r = F.ws_damage(scenario())

        assert.near(97 * EPDIF * (0.95 + 0.75), r.expected, 1e-9)
        assert.are.equal(2, r.swings)
    end)

    it('applies fTP only to the first hit by default', function()
        -- TP 3000 -> fTP 2.0 on first hit only
        local r = F.ws_damage(scenario({ tp = 3000 }))

        assert.near(97 * EPDIF * (2.0 * 0.95 + 1.0 * 0.75), r.expected, 1e-9)
    end)

    it('carries fTP to all hits when multi_hit_ftp is set', function()
        local r = F.ws_damage(scenario(
        {
            tp = 3000,
            ws = { ftp = { 1.0, 1.5, 2.0 }, num_hits = 2, mods = { str = 0.5 }, multi_hit_ftp = true },
        }))

        assert.near(97 * EPDIF * 2.0 * (0.95 + 0.75), r.expected, 1e-9)
    end)

    it('adds an unfloored offhand hit at the 95% cap', function()
        -- 1H axe, 1 hit + offhand:
        --   offhandBase = 30 + 6 + 41.5 = 77.5 (NOT floored)
        --   first hit cap 0.99 (1H main), offhand 75% raw
        local r = F.ws_damage(scenario(
        {
            weapon      = 'axe',
            offhand_dmg = 30,
            ws          = { ftp = { 1.0, 1.5, 2.0 }, num_hits = 1, mods = { str = 0.5 } },
        }))

        assert.near(77.5, r.offhand_base, 1e-12)
        assert.are.equal(0.99, r.first_hit_rate)
        assert.are.equal(0.75, r.offhand_hit_rate)
        assert.near(EPDIF * (97 * 0.99 + 77.5 * 0.75), r.expected, 1e-9)
        assert.are.equal(2, r.swings)
    end)

    it('applies the WS attack multiplier to pDIF', function()
        -- atk_varies 2.0: attack 300 vs def 300 -> wRatio 2
        local r = F.ws_damage(scenario(
        {
            attack = 300,
            ws     = { ftp = { 1.0, 1.5, 2.0 }, num_hits = 1, mods = { str = 0.5 }, atk_varies = 2.0 },
        }))

        assert.near(2.0, r.pdif.wratio, 1e-12)
    end)

    it('only crits when crit_varies is present', function()
        local plain = F.ws_damage(scenario())

        assert.are.equal(0, plain.crit_rate)
        assert.is_nil(plain.pdif_crit)

        local crit = F.ws_damage(scenario(
        {
            tp         = 2000,
            stats      = { str = 100, dex = 80 },
            target_agi = 60,
            ws         =
            {
                ftp         = { 1.0, 1.5, 2.0 },
                num_hits    = 1,
                mods        = { str = 0.5 },
                crit_varies = { 0.1, 0.25, 0.5 },
            },
        }))

        -- 0.05 base + 0.03 dDEX(20) + 0.25 TP factor
        assert.near(0.33, crit.crit_rate, 1e-12)
        assert.near(
            0.67 * crit.pdif.expected + 0.33 * crit.pdif_crit.expected,
            crit.expected_pdif, 1e-12)
    end)

    it('adds H2H natural damage to both hands', function()
        -- h2h_skill 100 -> natural 14; D 10 + 14 = 24 per hand
        -- mainBase = floor(24 + 2) = 26, offhandBase = 26
        local r = F.ws_damage(
        {
            weapon_dmg     = 10,
            offhand_dmg    = 0, -- ignored: H2H mirrors the main hand
            h2h_skill      = 100,
            fstr           = 2,
            stats          = {},
            ws             = { num_hits = 1, mods = {} },
            tp             = 1000,
            attack         = 600,
            defense        = 300,
            acc            = 300,
            eva            = 300,
            attacker_level = 75,
            target_level   = 75,
            alpha          = 0.83,
            profile        = 'lsb',
        })

        assert.are.equal(26, r.main_base)
        assert.near(26, r.offhand_base, 1e-12)
        -- H2H uses the 99% ceiling (lsb profile)
        assert.are.equal(0.99, r.first_hit_rate)
    end)

    it('selects WSC alpha from the profile', function()
        local base =
        {
            weapon_dmg     = 50,
            fstr           = 6,
            stats          = { str = 100 },
            ws             = { ftp = { 1.0, 1.5, 2.0 }, num_hits = 1, mods = { str = 0.5 } },
            tp             = 1000,
            attack         = 600,
            defense        = 300,
            acc            = 300,
            eva            = 300,
            attacker_level = 75,
            target_level   = 75,
            weapon         = 'great_axe',
        }

        -- Phoenix (default): legacy alpha(75) = 0.83
        --   mainBase = floor(50 + 6 + 50 * 0.83) = 97
        local phoenix = F.ws_damage(base)

        assert.near(0.83, phoenix.alpha, 1e-12)
        assert.are.equal(97, phoenix.main_base)

        -- lsb: Adoulin rules, alpha = 1
        --   mainBase = floor(50 + 6 + 50) = 106
        base.profile = 'lsb'
        local lsb = F.ws_damage(base)

        assert.near(1, lsb.alpha, 1e-12)
        assert.are.equal(106, lsb.main_base)
    end)

    it('caps Phoenix WS pDIF at the era 2.0 ceiling', function()
        -- Same scenario under the phoenix profile: wRatio 2 great axe
        -- E[pDIF] = (1.5400390625 + 2.0)/2 * 1.025 = 1.81427001953125
        -- 2H hit caps are 0.95 under both profiles, so only pDIF moves.
        local r = F.ws_damage(scenario({ profile = 'phoenix' }))

        assert.near(1.81427001953125, r.expected_pdif, 1e-12)
        assert.near(97 * 1.81427001953125 * (0.95 + 0.75), r.expected, 1e-9)
    end)

    it('caps total swings at 8', function()
        local r = F.ws_damage(scenario(
        {
            weapon      = 'axe',
            offhand_dmg = 30,
            ws          = { ftp = { 1.0, 1.5, 2.0 }, num_hits = 8, mods = { str = 0.5 } },
        }))

        assert.are.equal(8, r.swings)
    end)
end)

-- =====================================================================
describe('melee swing', function()
    it('combines base damage, expected pDIF and hit rate', function()
        -- D 50 + fSTR 6 = 56; capped dagger pDIF E = 3.33125; 75% hit
        local r = F.melee_swing(
        {
            weapon_dmg = 50,
            fstr       = 6,
            attack     = 2500,
            defense    = 500,
            weapon     = 'dagger',
            acc        = 300,
            eva        = 300,
            profile    = 'lsb',
        })

        assert.are.equal(56, r.base)
        assert.are.equal(0.75, r.hit_rate)
        assert.near(56 * 3.33125 * 0.75, r.expected, 1e-9)
    end)

    it('blends crit rate into expected pDIF', function()
        local r = F.melee_swing(
        {
            weapon_dmg = 50,
            fstr       = 6,
            attack     = 1000,
            defense    = 500,
            weapon     = 'scythe',
            acc        = 300,
            eva        = 300,
            crit_rate  = 0.10,
            profile    = 'lsb',
        })

        -- non-crit wRatio 2: upper 2.375, lower 1577/1024
        --   E_nc = (1.5400390625 + 2.375)/2 * 1.025 = 2.00645751953125
        -- crit wRatio 3 (cap 5): E_c = 3.075
        assert.near(0.9 * 2.00645751953125 + 0.1 * 3.075, r.expected_pdif, 1e-12)
    end)
end)

-- =====================================================================
describe('module hygiene', function()
    it('does not leak globals', function()
        package.loaded['formulas'] = nil

        local before = {}

        for key in pairs(_G) do
            before[key] = true
        end

        require('formulas')

        for key in pairs(_G) do
            assert.is_true(before[key] == true, 'leaked global: ' .. tostring(key))
        end
    end)
end)

if WHETSTONE_TEST_SUMMARY then
    WHETSTONE_TEST_SUMMARY()
end
